### ISSUE TITLE
Is there any information on how to run the app?

### ISSUE THREAD

**Issue by joselor** [barbaramartina/swiftuicatalog#43]
Sorry, I am new to the ecosystem. Do you have any information on how to run the app?

**Comment by frnkschmtt** [comment]
Hi @barbaramartina, I like the idea of this repo but at first I was also looking for a sample xcodeproj/xcworkspace file.
I believe it would lower the hurdle to get started with the catalog - especially for devs who are new to SwiftUI or iOS in general.
It could be also interesting to showcase SwiftUI controls look and feel not only on iOS but also on the other Apple platforms (watchOS, macOS, visionOS) by adding a multi platform sample app.

If you think this would be helpful, I'm happy to file a PR with a generic Xcode project.

**Comment by barbaramartina** [comment]
Hi Frank. 
Thanks so much for your interest first :)we started with a project in the repo and then, due to conflicts and potential team IDs collisions we removed them. It's very easy to make a project out of the source files. You just have to create a new project with swift UI and drag and drop the files there. This is how we want to handle it. 
I personally release the app to the App Store and for the moment we showcase it in iPhone and iPad. I would be nice to showcase it in MacOS too, but there is designs and assets preparation for the release to the App Store which require a lot of work. So developers can directly run the code locally in MacOS with any adjustments they need. 
I think that completing the still empty examples would be a more ground contribution. There are still some views that do not have examples. 
Another alternative is to start reviewing the warnings that we are having since we still didn't adapt to iOS 17. 
And another alternative is also start adding iOS 17 specific examples. 
What do you think about these other contribution alternatives?
